#!/bin/bash

echo "🚀 SUBIENDO CÓDIGO A GITHUB"
echo "=============================="
echo ""
echo "📍 Repositorio: https://github.com/emmanuellhti24-jpg/prueba_wifi.git"
echo "🌿 Rama: main"
echo ""
echo "⚠️  IMPORTANTE: GitHub te pedirá autenticación"
echo ""
echo "Opciones de autenticación:"
echo ""
echo "1️⃣  OPCIÓN 1: Personal Access Token (Recomendado)"
echo "   - Usuario: emmanuellhti24-jpg"
echo "   - Password: [Tu Personal Access Token]"
echo ""
echo "   Crear token en: https://github.com/settings/tokens"
echo "   - Click 'Generate new token (classic)'"
echo "   - Nombre: 'Momoys Deploy'"
echo "   - Permisos: Marca 'repo'"
echo "   - Copia el token y úsalo como contraseña"
echo ""
echo "2️⃣  OPCIÓN 2: GitHub CLI (gh)"
echo "   gh auth login"
echo "   gh repo sync"
echo ""
echo "=============================="
echo ""
echo "Ejecutando git push..."
echo ""

git push -u origin main
